### ISSUE TITLE
How to split image-registry

### ISSUE THREAD

**Issue by deads2k** [openshift/image-registry#1]
To create this repo, I did...

 1. clone openshift/origin
 2. delete everything except cmd/dockerregistry and pkg/dockerregistry
 3. clean git history
 4. rewrite imports to re-root this repo at `openshift/image-registry`
 5. create a glide.yaml to vendor dependencies
 6. create the upstream patch required to have the conflicting (for now) docker/distribution vendor
 7. make sure that `go build github.com/openshift/image-registry/cmd/dockerregistry` produces a binary

@bparees @dmage @smarterclayton @liggitt @mfojtik @derekwaynecarr    Let's talk here about whether or not we should use this as a starting point and bring in what's needed from here.  

I see next steps as:

 1. create a Makefile for build and unit test @stevekuznetsov 
 2. move the image producing pieces here @stevekuznetsov 
 3. convert existing openshift/origin integration tests for the registry to integration or e2e tests in this repo @bparees 
 4. update openshift/origin CI for new master (after we fork 3.7) to use the latest available image-registry image.

**Comment by stevekuznetsov** [comment]
Minimum viable impl for 1-3 is to re-add `hack/` and `test/` dir from Origin

**Comment by deads2k** [comment]
> Minimum viable impl for 1-3 is to re-add hack/ and test/ dir from Origin

That's not viable to test-integration to test-extended.  The tests won't work against the levels we want.

You like that unit test script?  I can copy that in.

**Comment by stevekuznetsov** [comment]
> You like that unit test script? I can copy that in.

I mean we can either start with `go build` and `go test` and `imagebuilder` and work our way up in complexity until we get something functional, or just copy and run. I see arguments for both but right now I do not have the bandwidth to start from 0 and iterate. Up to you.

**Comment by deads2k** [comment]
Now with working travis for build and unit test.

@smarterclayton @derekwaynecarr we're going to need images and I don't know how to make that black magic work.

**Comment by derekwaynecarr** [comment]
@deads2k i will pair you up with someone that just went through the process.

**Comment by mfojtik** [comment]
@deads2k this looks great to me, I expected this to be clone of origin but I see you did the vendored approach.

**Comment by deads2k** [comment]
> @deads2k this looks great to me, I expected this to be clone of origin but I see you did the vendored approach.

Yeah, otherwise its a time bomb for the next guy and I know who would be tapped.
