### ISSUE TITLE
Sync labels with openshift/origin

### ISSUE THREAD

**Issue by legionus** [openshift/image-registry#10]
The repository has no labels for priorities, statuses, kinds, so the bots commands do not work. I can not create or synchronize them because I do not have permissions for that.

**Comment by bparees** [comment]
i've created the basic set, if you know of others that we explicitly need please let me know and i'll add them.

@stevekuznetsov this looks like another good candidate for "default stuff that a new repository needs".  Do you have any way to sync the origin labels into this repository?  copying them by hand is pretty tedious.

**Comment by bparees** [comment]
looks like maybe this tool can do it but we'd have to grant it access:
https://medium.com/@dtinth/how-to-copy-github-labels-from-one-project-to-another-1857adc73e0f

**Comment by legionus** [comment]
Please add also:
- `kind/question`
- `area/usability`
- `area/tests`
- `area/techdebt`
- `area/security`
- `area/performance`
- `area/compatibility`
- `area/documentation`

**Comment by bparees** [comment]
done.

@stevekuznetsov i'm closing this but i'd still appreciate some follow up on sync'ing/init'ing labels for new repositories.

**Comment by kargakis** [comment]
https://trello.com/c/tJNlpkr4/451-sync-github-labels-across-repositories

**Comment by legionus** [comment]
@bparees can you give еру permissions to me, @dmage and @miminar to assign labels on new and existent issues? I mean not only by command to bot, but manually too.

**Comment by bparees** [comment]
@legionus try now.

**Comment by legionus** [comment]
@bparees thanks, it works.
