### ISSUE TITLE
image-registry is tied to Sirupsen (uppercase)

### ISSUE THREAD

**Issue by bparees** [openshift/image-registry#112]
This means we can't pick up newer kube deps (which are tied to sirupsen lowercase)

It looks like the master branch of docker distribution has handled this(moved to lowercase), so we should probably do what we proposed a few weeks ago and move up to master.

The only alternative I see (other than getting left behind on really old kube deps) would be to do a carry patch for docker distribution to switch it to lowercase sirupsen and that seems terrible.

@legionus @dmage any other options you see?

**Comment by bparees** [comment]
@deads2k fyi when you wonder why image-registry is still using kube 1.9 deps.

**Comment by deads2k** [comment]
> @deads2k fyi when you wonder why image-registry is still using kube 1.9 deps.

@derekwaynecarr time bombs.  Luckily we got this split out just in time.

**Comment by bparees** [comment]
for what it's worth, cherry-picking+carrying the commit actually doesn't look too bad:
https://github.com/docker/distribution/commit/a97d7c0c155be14d1380c075d3197a5d89c2abc2

the main problem is they did that after moving to `dep`, so we'd have to manage the godeps changes.

**Comment by legionus** [comment]
After rebase, we no longer use the `github.com/Sirupsen/logrus`.

```sh
$ git grep -c Sirupsen 
glide.lock:1
glide.yaml:1
vendor/github.com/bshuster-repo/logrus-logstash-hook/CHANGELOG.md:1
vendor/github.com/bshuster-repo/logrus-logstash-hook/logstash_formatter.go:1
vendor/github.com/google/cadvisor/Godeps/Godeps.json:1

$ git grep sirupsen |wc -l
330
```

**Comment by bparees** [comment]
@legionus looks like it's still in our glide.yaml, can you submit a PR removing it that closes this issue?

**Comment by bparees** [comment]
and bump us to kube 1.11 deps while you're at it.
