### ISSUE TITLE
Add codecov.io

### ISSUE THREAD

**Issue by legionus** [openshift/image-registry#13]
I suggest to add the [code coverage](https://codecov.io/) support for `image-registry` repository.

https://github.com/apps/codecov
https://github.com/marketplace/codecov

/cc @bparees  @dmage @miminar

**Comment by bparees** [comment]
i'd like to keep us as aligned w/ the rest of the repos as possible so we don't end up with different processes/configurations/reports.  If @smarterclayton is on board with it, though, it's fine with me.

**Comment by legionus** [comment]
@bparees @smarterclayton this service is used in the `docker/distribution` and is very useful. This is especially useful now, when we change and add tests. It is very good to see test coverage.

**Comment by smarterclayton** [comment]
Do you have to give any sort of special privileges to the bot?  If it
requires anything other than read access we'll need to go through a
security review of it.

**Comment by legionus** [comment]
@smarterclayton I just tried to install it on my personal account. He wants:

- Read access to code
- Read access to administration, issues, members, and metadata
- Read and write access to commit statuses and pull requests

**Comment by legionus** [comment]
not needed.
