### ISSUE TITLE
Update regions

### ISSUE THREAD

**Issue by pweil-** [openshift/image-registry#153]
Via https://github.com/openshift/origin/issues/12454#issuecomment-459635222
> @pweil- +1 for cn-northwest.

Regions are pulled from the generated endpoints in aws-sdk-go.  It looks like our version is 1.12.36.  Latest is 1.16.26 which includes the cn-northwest region mentioned in the request.  

@tj13 To set expectations, this requires evaluation of risk when we rebase new versions of the upstream repo since features may be pulled in, removed, changed, etc and must be tested.  Not a quick update and will be prioritized against the existing feature queue.  Thanks for the request!

**Comment by bparees** [comment]
converted to jira:
https://jira.coreos.com/browse/DEVEXP-264
