### ISSUE TITLE
Problems with non AWS-S3 storage backend

### ISSUE THREAD

**Issue by iceman91176** [openshift/image-registry#172]
We are experiencing lots of problems when using a rados-gw-based S3 backend (ceph luminous) for the image-registr (3.11). We are not able to push any images, pushing is aborted with an HTTP-500 error
When looking at the raw requests we see problems with multipart uploads.
After searching the web for some hours it seems that we are not the only ones having problems with  rados-gw-s3. 
It seems to related to AWS GO SDK which didn't properly support other backends than aws.
for example see the following issue for docker-registry https://github.com/docker/distribution/pull/2563

Any ideas / clues ?

Thank you

**Comment by dmage** [comment]
In general, if API claims to be compatible with S3, but the official client doesn't work with it, either API or the client should be fixed. If updating aws-go-sdk is enough, we updated aws-go-sdk to 1.17.2 in 4.0. So the next release won't have this problem. You may also check other gateway APIs, for example Swift API.
