### ISSUE TITLE
[Need help] Is openshift internal registry has token service api ?

### ISSUE THREAD

**Issue by lcnsir** [openshift/image-registry#180]
As other image registry solution

there is a token service api like
```
curl -k -s -u admin:password "https://xxxx/service/token?service=token-service&scope=repository:project/image-name:pull,push" 
```
we can use it to get a access token with different permission

Then use it to access registry api for example list all image name:
```
curl -k -s -H "Authorization: Bearer $token" "https://xxxxx:8500/v2/_catalog" | python -m json.tool
```

After check the doc of openshift internal image registry, seems there are no token services like that, and we can use servicaccount token of kube-system or user token to access regstry api without permission limitation.

Could you guys help to clarify if there is a token service for openshift image registry ?

Thanks very much.

**Comment by dmage** [comment]
There is the endpoint `/openshift/token`. You should get it from the Www-Authenticate header:

```
$ curl -I 'https://registry.openshift.example.com/v2/' | grep ^Www-Authenticate:
Www-Authenticate: Bearer realm="https://registry.openshift.example.com/openshift/token"
```

And you should follow this protocol if you want to be compatible with other registries (and with future versions of the integrated registry). But the current implementation just checks the token and returns it back to the client, so it doesn't have the ability to limit the scope of the token. If you want to have a token with a limited scope, you should create another user and give it different set of permissions using RBAC.

**Comment by lcnsir** [comment]
@dmage .thanks for your respoces,

The token service is works
```
curl -k -s -u admin:Yp6SF3zMcoJamundefined0QlJkPmIUmOVXX4ZcBnOM8p2FW9PCA "https://docker-registry.default.svc:5000/openshift/token"
{"access_token":"Yp6SF3zMcoJamundefined0QlJkPmIUmOVXX4ZcBnOM8p2FW9PCA","token":"Yp6SF3zMcoJamundefined0QlJkPmIUmOVXX4ZcBnOM8p2FW9PCA"}
```
but the WWW-Authenticate header access failed 
```
curl -k -s -H "WWW-Authorization: Bearer Yp6SF3zMcoJamundefined0QlJkPmIUmOVXX4ZcBnOM8p2FW9PCA" "https://docker-registry.default.svc:5000/v2/openshift/rhpam71-businesscentral-indexing-openshift/manifests/1.0"
{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"repository","Class":"","Name":"openshift/rhpam71-businesscentral-indexing-openshift","Action":"pull"}]}]}
[ec2-user@still-piranha-master ~]$ curl -k -s
```

Then I try it successfully to call the registry by Authenticate header
```
[ec2-user@still-piranha-master ~]$ curl -k -s -H "Authorization: Bearer Yp6SF3zMcoJamundefined0QlJkPmIUmOVXX4ZcBnOM8p2FW9PCA" "https://docker-registry.default.svc:5000/v2/openshift/rhpam71-businesscentral-indexing-openshift/manifests/1.0"
{
   "schemaVersion": 1,
   "name": "openshift/rhpam71-businesscentral-indexing-openshift",
   "tag": "1.0",
   "architecture": "amd64",
   "fsLayers": [
      {
         "blobSum": "sha256:f3333ec81dd28ef84823693def1894b8ea085924da4809c8e91f2fd9ea9878c9"
      },
      {
         "blobSum": "sha256:7a92edd89a4672cf1334075b395bb804e2600f9a62207a0428e78e3dd770c708"
      },
      {
         "blobSum": "sha256:e3479b324492384d3a7fc5420f62bbf4e7cb0a161325c7cda4d0cbfb577d70ff"
      },
      {
         "blobSum": "sha256:8d9c78c7f9887170d08c57ec73b21e469b4120682a2e82883217535294878c5d"
      },
      {
         "blobSum": "sha256:e17262bc23414bd3c0e9808ad7a87b055fe5afec386da42115a839ea2083d233"
      },
      {
         "blobSum": "sha256:378837c0e24ad4a2e33f0eb3d68dc0c31d9a7dbbd5357d4acafec1d3a7930602"
      }
```

So the Authenticate header is the one actually works ?

**Comment by dmage** [comment]
`WWW-Authorization` is the header that the client should expect to receive from the server.
`Authorization` is the header that client should use to sent its credentials.
