### ISSUE TITLE
redirect parameter not working

### ISSUE THREAD

**Issue by rhnewtron** [openshift/image-registry#182]
When using the docker-registry on azure the registry uses SAS Tokens and redirect to redirect clients to the blob URL's for download / upload. If you have VNet Security enabled, this does not work, unless you remove this access (403 is returned). 

The upstream registry provides a parameter for this (redirect), it is part of the documentation https://docs.openshift.com/container-platform/3.11/install_config/registry/extended_registry_configuration.html#docker-registry-configuration-reference-storage, however it is not working. 

I need a way to disable redirects.

**Comment by dmage** [comment]
@rhnewtron can you elaborate on the parameter? The upstream registry has 4 parameters for the Azure storage driver: accountname, accountkey, container, and realm [[1]].

[1]: https://docs.docker.com/registry/storage-drivers/azure/

**Comment by rhnewtron** [comment]
It's about this: 
```
storage:
  ....
  redirect:
    disable: false
```

Described here https://docs.openshift.com/container-platform/3.11/install_config/registry/extended_registry_configuration.html#docker-registry-configuration-reference-storage

I need 
```
storage:
  redirect:
    disable: true
```

**Comment by dmage** [comment]
You can set the environment variable REGISTRY_STORAGE_REDIRECT_DISABLE=true

**Comment by rhnewtron** [comment]
This was a great tipp. I set the Environment on the Registry and now I can push and pull Images with the Azure Backend from the Registry via the exposed route without granting vnet access to everyone. I think this is very valuable for the documentation.

env:
```
            - name: REGISTRY_STORAGE_REDIRECT_DISABLE
              value: "true"
```

**Comment by rhnewtron** [comment]
From my side the issue can be closed. However updating the documentation for azure specifics (vnet security for storage accounts) may be a great follow up ticket.

**Comment by adambkaplan** [comment]
@dmage something we need to factor in to the image-registry-operator?

**Comment by dmage** [comment]
@adambkaplan we may want to expose this setting for UPI installations. We need to weigh benefits of vnet security

**Comment by bparees** [comment]
> @adambkaplan we may want to expose this setting for UPI installations.

why would we make a distinction on config options for ipi vs upi?

the critical issue in my mind is what we default content redirect to be enabled on azure installations, based on whether vnet security is on or not.

**Comment by dmage** [comment]
@bparees we don't enable vnet security on IPI, so we don't need this option there. But this option will be available for IPI and UPI.

**Comment by dmage** [comment]
The option disableRedirects is added to the image registry operator config.
