### ISSUE TITLE
openshift create ca server certificate for docker registry

### ISSUE THREAD

**Issue by get2arun** [openshift/image-registry#205]
How to create the "ca.crt" file in order to login to openshift docker registry. The [URL](https://github.com/openshift/origin/issues/21691) have the command to create ca.crt file in the docker registry and this ca.crt to be copied to docker client machine. here is the command.
>  oc adm ca create-server-cert \
>     --signer-cert=/etc/origin/master/ca.crt \
>     --signer-key=/etc/origin/master/ca.key \
>     --signer-serial=/etc/origin/master/ca.serial.txt \
>     --hostnames='docker-registry-default.company.cl,openshift.lab.company.corp,<ip_registry_host>,<ip_oc_cluster>' \
>     --cert=/etc/secrets/registry.crt \
>     --key=/etc/secrets/registry.key

I have the registry.key and registry.crt file from default namespace >resources > secrets > registry-certificates, copied to /etc/secrets in the docker client machine.

How can I login to openshift docker registry host or container? 
How to get the credentials to login to openshift docker registry?
Where to execute the command "oc adm ca create-server-cert", docker server or client machine?
Could you please someone explain the values to pass for options signer-cert, signer-key, siger-serial, what hostnames and ip address to be added?

**Comment by dmage** [comment]
> I have the registry.key and registry.crt file from default namespace >resources > secrets > registry-certificates, copied to /etc/secrets in the docker client machine.

You shouldn't copy the server certificate to clients. This certificate is only for the server and its key should be kept secret.

How to expose the registry and access it is described in depth in our documentation: https://docs.openshift.com/container-platform/4.2/registry/securing-exposing-registry.html
