### ISSUE TITLE
registry image reports "unknown" openshift version

### ISSUE THREAD

**Issue by bparees** [openshift/image-registry#26]
time="2017-12-11T18:50:48.773847179Z" level=info msg="start registry" distribution_version="v2.6.2+unknown" go.version=go1.8.3 instance.id=0bfa960a-ac57-4138-abf9-f9445aa5eed7 kubernetes_version=v1.7.6+$Format:%h$ openshift_version=unknown

**Comment by bparees** [comment]
the kubernetes version output is also messed up:
`kubernetes_version=v1.7.6+$Format:%h$ `

at a minimum the "Format" shouldn't be there (should be a git commit).

**Comment by dmage** [comment]
That is expected output, we need to remove dependencies on origin and I'm going to remove this fields at all, because they are for origin. What do you expect to see there?

**Comment by bparees** [comment]
> That is expected output, we need to remove dependencies on origin and I'm going to remove this fields at all, because they are for origin. What do you expect to see there?

Well i think we need to discuss as an org what we expect (should the image-registry report a consistent version like "v3.9" itself?  if so, should it get that value from a common location rather than each repo having to maintain/bump the version itself?)

But at a minimum i'd expect/want the git commit that was used to build the image.

So `openshift_registry_version=vX.Y+commitid` is what i'd expect/want.

Where the source of X.Y is TBD.

**Comment by bparees** [comment]
@smarterclayton what's the plan for providing common version numbers to different components like this?  Is the build tooling supposed to handle it for us?  Some other mechanism?
