### ISSUE TITLE
Track client operations using tokens

### ISSUE THREAD

**Issue by dmage** [openshift/image-registry#43]
Docker for each operation (pull, push) gets a new OAuth2 token. The current implementation of the token endpoint is basically a stub.

We can use this feature to tie the sequence of requests together:

  1. /openshift/token endpoint returns a signed tuple (openshift token, random id) as a registry token.
  2. On each operation, the registry checks the signature of the provided token.
  3. If the signature is valid, the registry extracts the random id and puts it into the log context as  `token.id` (like `http.request.id`).

While Docker doesn't share tokens between operations, this token id should be helpful for debugging and analytics.

**Comment by bparees** [comment]
@dmage @legionus can you guys fill in the description on this issue?

**Comment by bparees** [comment]
Also should this be a trello card instead?

**Comment by bparees** [comment]
trello'd: https://trello.com/c/lhawfbIW
