### ISSUE TITLE
Use latest version of origin in tests

### ISSUE THREAD

**Issue by dmage** [openshift/image-registry#51]
We want to test the master code against the latest version of origin. See #50.

At the same time, the code from the release-3.8 branch is supposed to be tested with origin's branch release-3.8. And when we'll have the release-3.9 branch, it should use origin from the branch release-3.9.

**Comment by bparees** [comment]
(we currently can't use "latest" because something changed in origin that is breaking our integration tests...sorting that out is the most urgent problem.  Getting our release branches using released versions of origin is secondary)

**Comment by bparees** [comment]
(and getting to the point where things that break out integration tests can't merge into origin is also a high secondary priority)

**Comment by stevekuznetsov** [comment]
You are OK building Origin in your jobs then, yeah? We'll just need to start the job from the base stage and build origin there/

**Comment by bparees** [comment]
> You are OK building Origin in your jobs then, yeah? We'll just need to start the job from the base stage and build origin there/

yes. we need to build the right origin branch though.

**Comment by stevekuznetsov** [comment]
Do you need intervention from me here? The branch of this repo being tested is provided as `${PULL_BASE_REF}` as specified [here](https://github.com/kubernetes/test-infra/tree/master/prow#job-evironment-variables). The step to build Origin would just be added in `aos-cd-jobs` as per usual.
