### ISSUE TITLE
Restore image signature workflow extended test

### ISSUE THREAD

**Issue by miminar** [openshift/image-registry#74]
Was openshift/origin#16344

The test existed in the origin repository: https://github.com/miminar/origin/blob/262b8bafff6b5f338e647c94bc9530121fc18131/test/extended/registry/signature.go

It was re-enabled in openshift/origin#17202 and removed one week later during a rebase to kube 1.8.1 (openshift/origin#17115) since it allegedly belongs to this repository.

**Comment by dmage** [comment]
duplicates #39

**Comment by miminar** [comment]
Ah, missed it, thanks.
