### ISSUE TITLE
TLS handshake timeout

### ISSUE THREAD

**Issue by pennpeng** [openshift/image-registry#77]
nternal error occurred: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/fd/fdd589482018b388e3ef90e087a41be78714966d43a01f3542f96af8df8ea49e/data?Expires=1524083159&Signature=T2Le~M3Tq8hta74USnsJmqUkPjIzby7uizQ7c7k7fgy28UxOuVLxyVYCsAweyoXllRc5Hzoexk0geaLePaZj-zP8PIZMmzyPq~-MBSlJz-4v1YrSB2uz~v-LjEHFhx43CUt~cJ5h4DZOa2Vvpw1pq7DRnYPhdbpdMU-fKO-EuTc_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: net/http: TLS handshake timeout. Timestamp: 2018-04-18T08:26:09Z Error count: 2 Edit image stream

**Comment by legionus** [comment]
This is a network issue. The intergrated registry got a timeout when trying to connect to `cloudfront.net`.
