### ISSUE TITLE
Run tests without "openshift start"

### ISSUE THREAD

**Issue by dmage** [openshift/image-registry#78]
There are rumours that "openshift start" will be removed in next versions of Origin. We should be ready to it.

**Comment by bparees** [comment]
True, is there anything our tests require that would be hard to achieve
with oc cluster up?


Ben Parees | OpenShift

**Comment by dmage** [comment]
`oc cluster up` can run only one cluster simultaneously. We'll need to rethink our tests.

**Comment by dmage** [comment]
@bparees my PR is incomplete and is only for pullthrough. It's less than 20% of total work. @miminar was more accurate in estimating: it's much bigger than 8.

**Comment by bparees** [comment]
Ok, thanks for the update. I'll try to find someone else to take a look at this.

**Comment by dmage** [comment]
This was fixed when TEST_KUBECONFIG was introduced.
