### ISSUE TITLE
Rework registry logging

### ISSUE THREAD

**Issue by legionus** [openshift/image-registry#80]
We need to change the approach to logging in such a way that one error message contained all the information (maximum information) necessary for the problem investigation. In this case, we can change the logging level to `error` and remove some of the debug messages that we have now.

After discussion with Oleg, we came to the conclusion that we can add prefixes to the error as it passes through our code.

disclaimer: We have to review all the errors (ideally they should be reproduced) and check whether there is enough information from each stage.

After we solve this, we can change the loglevel as suggested in #75 .

**Comment by dmage** [comment]
The best known example is https://github.com/openshift/image-registry/blob/d5a32198ec0f0477741e7e09166a1e491982d4c8/pkg/dockerregistry/server/blobdescriptorservice.go#L44

This condition shouldn't be just silently ignored.

https://github.com/openshift/image-registry/blob/d5a32198ec0f0477741e7e09166a1e491982d4c8/pkg/dockerregistry/server/blobdescriptorservice.go#L46-L48

This error should be logged as well. And this new log message should supersede the previous one.

https://github.com/openshift/image-registry/blob/d5a32198ec0f0477741e7e09166a1e491982d4c8/pkg/dockerregistry/server/blobdescriptorservice.go#L67

And here we can see abstraction leak. Sometimes this execution flow is related to pullthrough, sometimes is not. Most likely it will require refactoring to get better logs.

**Comment by bparees** [comment]
thanks @legionus @dmage it sounds like a promising approach, I look forward to discussing it further when i'm back in the office

**Comment by dmage** [comment]
Fixed by #110.
